project:
  type: website

website:
  page-navigation: true
  title: "MSSC 6250 - Spring 2025"
  description: "Homepage for MSSC 6250 - Statistical Machine Learning at Marquette University, Spring 2024."
  site-url: "https://mssc6250-s25.github.io/website/"

  repo-url: https://github.com/mssc6250-s25/website
  repo-actions: [edit, issue]

  open-graph: true

  # twitter-card:
  #   creator: "@minebocek"
  #   image: "images/twitter-card.png"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Cheng-Han Yu"
    background: "#b5e2ff"

  sidebar:
    background: "#b5e2ff"
    logo: "/images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/mssc6250-s25/website
        text: "GitHub organization"
      # - icon: code-square
      #   href: https://cmgr.oit.duke.edu/containers
      #   text: "RStudio Containers"
      - icon: person-fill
        href: https://d2l.mu.edu/d2l/home/589421
        text: "D2L"

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - section: "Course Information"
        contents:
          - href: course-news.qmd
            text: News/Annoucements
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          # - href: course-support.qmd
          #   text: Support
          # - href: course-team.qmd
          #   text: Teaching team
          - href: index.qmd
            text: Schedule
          # - href: course-links.qmd
          #   text: Useful links
          # - href: course-faq.qmd
          #   text: FAQ
      # - section: "Computing"
      #   contents:
      #     - href: computing-access.qmd
      #       text: Access
      #     - href: computing-troubleshooting.qmd
      #       text: Troubleshooting

      - section: "Midterm Project Presentation"
        contents:
          - href: present-description.qmd
            text: Guideline and Policy
          - href: present-work.qmd
            text: Topics and Works
      - section: "Final Project"
        contents:
          - href: project-description.qmd
            text: Guideline and Policy
          # - href: project-description-5780.qmd
          #   text: Guideline for MATH 5780
          - href: project-work.qmd
            text: Topics and Works

      - section: "Weekly Materials"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"
          - href: weeks/week-2.qmd
            text: "Week 2"
          - href: weeks/week-3.qmd
            text: "Week 3"
          - href: weeks/week-4.qmd
            text: "Week 4"
          - href: weeks/week-5.qmd
            text: "Week 5"
          - href: weeks/week-6.qmd
            text: "Week 6"
          - href: weeks/week-7.qmd
            text: "Week 7"
          - href: weeks/week-8.qmd
            text: "Week 8"
          - href: weeks/week-9.qmd
            text: "Week 9"
          - href: weeks/week-10.qmd
            text: "Week 10"
          - href: weeks/week-11.qmd
            text: "Week 11"
          - href: weeks/week-12.qmd
            text: "Week 12"
          - href: weeks/week-13.qmd
            text: "Week 13"
          - href: weeks/week-14.qmd
            text: "Week 14"
          - href: weeks/week-15.qmd
            text: "Week 15"
          - href: weeks/week-16.qmd
            text: "Week 16"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual