---
title: "Midterm Project II Proposal and Presentation"
---

## Presentation Order

The presentation order is determined by the time you sent me your member info (`c("John", "Jeremy", "Praful")` is the first to let me know, followed by `c("Sajjad", "Tanjina", "Dewan")`, etc) and random sampling as follows.

```{r}
team_lst <- list(c("John", "Jeremy", "Praful"), 
                 c("Sajjad", "Tanjina", "Dewan"),
                 c("Ethan", "Navid", "Sylvester"), 
                 c("Violet", "Vanessa", "Michele"), 
                 c("Rakesh", "Daniel", "Jeremy"), 
                 c("Sai", "Rohith", "Shristi"))
set.seed(2025)
team_lst[sample(1:6, 6)]
```

## Project Materials

-   [**Group 1 (Rakesh, Daniel, Jeremy)**]{.blue}: [proposal](./documents/project_proposal/project2/proposal2_rakesh_danial_jeremy.pdf)

-   [**Group 2 (Violet, Vanessa, Michele)**]{.blue}: [proposal](./documents/project_proposal/project2/proposal2_violet_venessa_michele.pdf)

-   [**Group 3 (Sai, Rohith, Shristi)**]{.blue} : [proposal](./documents/project_proposal/project2/proposal2_sai_rohith_shristi.pdf)

-   [**Group 4 (Sajjad, Tanjina, Dewan)**]{.blue}: [proposal](./documents/project_proposal/project2/proposal2_tanjina_sajjad_dewan.pdf)

-   [**Group 5 (John, Jeremy, Praful)**]{.blue}: [proposal](./documents/project_proposal/project2/proposal2_john_jeremy_praful.pdf)

-   [**Group 6 (Ethan, Navid, Sylvester)**]{.blue}: [proposal](./documents/project_proposal/project2/proposal2_ethan_navid_sylvester.pdf)
